---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sample-app"
  namespace: "shipping-dev"
  labels:
    app: "sample-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "sample-app"
  template:
    metadata:
      labels:
        app: "sample-app"
    spec:
      containers:
      - name: "helloworld"
        image: "dockercloud/hello-world"
        ports:
        - containerPort: 80

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sample-app-hpa-ukaw"
  namespace: "shipping-dev"
  labels:
    app: "sample-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sample-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80