---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sample-app-service"
  namespace: "shipping-dev"
  labels:
    app: "sample-app"
    app.kubernetes.io/managed-by: "configmanagement.gke.io"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "sample-app"
  type: "LoadBalancer"
  loadBalancerIP: ""